# Generated by Django 4.2.16 on 2026-06-19 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ml_label', models.CharField(choices=[('benign', 'Benign'), ('defacement', 'Defacement'), ('phishing', 'Phishing'), ('malware', 'Malware')], default='benign', max_length=20)),
                ('ml_confidence', models.FloatField(default=0.0)),
                ('ml_risk_score', models.IntegerField(default=0)),
                ('final_risk_score', models.IntegerField(default=0)),
                ('threat_level', models.CharField(choices=[('safe', 'Safe'), ('low_risk', 'Low Risk'), ('suspicious', 'Suspicious'), ('high_risk', 'High Risk'), ('malicious', 'Malicious')], default='safe', max_length=20)),
                ('threat_intel_json', models.TextField(blank=True, default='{}')),
                ('features_json', models.TextField(blank=True, default='{}')),
                ('heuristic_json', models.TextField(blank=True, default='{}')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL Scan',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('vt_malicious', models.IntegerField(default=0)),
                ('vt_suspicious', models.IntegerField(default=0)),
                ('vt_harmless', models.IntegerField(default=0)),
                ('vt_total', models.IntegerField(default=0)),
                ('vt_permalink', models.URLField(blank=True)),
                ('gsb_is_safe', models.BooleanField(default=True)),
                ('gsb_threats', models.TextField(blank=True)),
                ('pt_in_database', models.BooleanField(default=False)),
                ('pt_verified', models.BooleanField(default=False)),
                ('abuse_confidence', models.IntegerField(default=0)),
                ('abuse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('abuse_country', models.CharField(blank=True, max_length=10)),
                ('heuristic_score', models.IntegerField(default=0)),
                ('recommendation', models.TextField(blank=True)),
                ('url_scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='security.urlscan')),
            ],
            options={
                'verbose_name': 'Scan Report',
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_uploads/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decoded_url', models.TextField(blank=True)),
                ('decode_success', models.BooleanField(default=False)),
                ('decode_error', models.TextField(blank=True)),
                ('url_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.urlscan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Scan',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
